language: python
sudo: required

matrix:
  include:
    - dist: bionic
      python: 3.7
      env: dist="18.04 LTS bionic"

before_install:
  # Pull and build containernet
  - sudo apt-get update -qq
  - sudo apt-get install -qq vlan
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ansible libffi-dev libssl-dev
  - git clone git@github.com:containernet/containernet
  - cd containernet/ansible
  - travis_wait 60 sudo ansible-playbook -i "localhost," -c local install.yml

# install ContainerNet-GraphML Module
install:
    - cd /ContainerNet-GraphML
    - pip install -e .
# run tests
script:
  # style check
  - flake8 scr
  - travis_wait 60 docker build --tag ping examples/ping/
  - sudo python examples/ping
notifications:
  email:
    on_success: change
    on_failure: always