language: python
sudo: required

matrix:
  include:
    - dist: bionic
      python: 3.7
      env: dist="18.04 LTS bionic"

before_install:
  # Pull and build containernet
  - sudo apt-get update -qq
  - sudo apt-get install -qq vlan flake8
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ansible libffi-dev libssl-dev
  - git clone https://github.com/containernet/containernet.git
  - cd containernet/ansible
  - travis_wait 60 sudo ansible-playbook -i "localhost," -c local install.yml

# install ContainerNet-GraphML Module
install:
    - cd ../..
    - sudo pip3 install -e .
# run tests
script:
  # style check
  - flake8 src
  - travis_wait 60 docker build --tag ping examples/ping/
  - sudo python3 examples/ping/cn_ping_test.py
notifications:
  email:
    on_success: change
    on_failure: always